### ISSUE TITLE
Use HTML rather that Jade

### ISSUE THREAD

**Issue by chmelevskij** [GlaWebDev/glaWebDev#2]
Hi, would you mind switching Jade templating to HTML? It's just I kind of prefer good old HTML and it's definitely would be better for everybody els to learn it first.

**Comment by modelorona** [comment]
How about ejs?

**Comment by neildocherty** [comment]
I agree that HTML would make sense for beginners. It may not be an issue as this is a small thing to be done just now. They can simply copy and edit the requisite files and it's always good to learn. 

I don't know if EJS looks any clearer than Jade(Pug) or HTML.

I used the express generator which defaults to Jade. We can easily change this to the Pug engine.

So, I'd stick with Jade for the time being. So that we can allow eveyone to complete the task. Then we can change the rendering engine to Pug (I believe the syntax is the same and it's easy enough to edit the file extensions).

I think it would make more sense to revisit this question when we take the project further. We will undoubtedly remove the files everyone is making just now and use a single template so won't be an issue.

**Comment by qaisern** [comment]
I agree with tom, its best to  keep it basic initially
